### PR TITLE
Allow state option to be overridden

### PR DESCRIPTION
**Pull request by cvinson**
Small change to avoid overwriting the passed in state param.

### CODE REVIEW

**Comment by analog-nico** [comment]
Hey @cvinson !

The changed code still always sets `options.state` to `true`. It should be `options.state = options.state === false ? false : true`.

However, the `state` parameter is intentionally set to `true` because this increases security. See https://developers.pinterest.com/docs/api/overview/ and search for "state". Why do you ever want to set it to `false`?

**Comment by analog-nico** [comment]
Or do you intend to pass your own state value? If yes, I am curious to know the use case! Thanks.

**Comment by analog-nico** [comment]
Any thoughts about its usage so that I have something I can add to the README?

**Comment by cvinson** [comment]
You are correct. Not sure what I was thinking there. I'll make those changes here shortly.

Passing my own state values is exactly my use case.

**Comment by analog-nico** [comment]
No, sorry. Your code is correct for passing strings. Just `false` wouldn't be possible. But disabling the additional security is anyway not a good idea.

I'll take it from here. Thanks for your contribution!

**Comment by analog-nico** [comment]
I just released version 0.4.0 which allows string values for `options.state`.

**Pull request merged**
